<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Accueil</title>
</head>
<body>
<h1>Page d'accueil</h1>
<p> salut <strong> <?php $nom ?> <?php $prenom ?> </strong></p>
<br>
<a href="logout.php">Déconnexion</a>

    
</body>
</html> -->


<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
	<div class="row">
    	 <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="border-radius: 16px;">
                        <div class="well profile col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                                <figure>
                                     <img src="<?=$photo?>" alt="" class="img-circle" style="width:75px;" id="user-img">
                                </figure>
                                <h5 style="text-align:center;"><strong id="user-name"><?= $prenom ?> <?= $nom ?></strong></h5>
                                <p style="text-align:center;font-size: smaller;" id="user-frid"><?php $id ?></p>
                                <p style="text-align:center;font-size: smaller;overflow-wrap: break-word;" id="user-email"><?= $nom ?>_<?= $prenom ?>_<?= $id ?>@pro-mail.com </p>
                                <p style="text-align:center;font-size: smaller;"><strong>A/C status: </strong><span class="tags" id="user-status">Active</span></p>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 divider text-center"></div>
                                <p style="text-align:center;font-size: smaller;"><strong>Job role</strong></p>
                                <p style="text-align:center;font-size: smaller;" id="user-role">Software Engineer</p>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 divider text-center"></div>
                                    <div class="col-lg-6 left" style="text-align:center;overflow-wrap: break-word;">
                                        <h4><p style="text-align: center;"><strong id="user-globe-rank">245 </strong></p></h4>           
                                        <p><small class="label label-success">Global Ranking</small></p>
                                        <!--<button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>-->
                                    </div>
                                    <div class=" col-lg-6 left" style="text-align:center;overflow-wrap: break-word;">
                                        <h4><p style="text-align: center;"><strong id="user-college-rank">245 </strong></p></h4>                   
                                        <p> <small class="label label-warning">College Ranking</small></p>
                                        
                                        
                                    </div>
                                    <button href="logout.php" class="btn btn-info btn-block"></button>
                                    <a class="btn btn-info btn-block" href="logout.php">Déconnexion</a>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>    
        </div>
	</div>
</div>